name: log

on: "workflow_dispatch"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: logging list of files
        run: ls
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: logging again
        run: ls
