name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm i
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download code
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: output contents
        run: ls
